### ISSUE TITLE
uskill localization

### ISSUE THREAD

**Issue by n0q** [n0q/hackmaster5e-fvtt#10]
universal skills are not localized yet.

**Comment by deidril** [comment]
Hi, i'm interrested to help on this project but i'm not a very good JS programmer. However i can help on json files related issues
About this issue, it needs to insert skills description from the free edition into the skill pack items ?

**Comment by n0q** [comment]
Hey there! I'm not sure if I have permission for descriptions, so I'd rather not go there yet. This issue is actually about translation.

I'm trying to use a language file for text (lang/en.json) rather than put raw English text everywhere. This is in case I ever have the means/need to translate the system into another language. The universal skills pack **is** using raw text, though. There's already a *HM.uskills* member which contains keys/values and I'm simply not using that when I build characters in modules/actor.js (at the bottom).

I think the easiest way would be for the universal-skills.db skill names to reference the file (Name them *'HM.uskill.gleaninfo'* instead of 'Glean Information', for example), and then in createActor, you translate each name with game.i18n.localize, and update all embedded documents so your changes stick.

Hackmaster only comes published in English afaik, but it's common (and good) practice to localize and I'd rather be ready for an unexpected book translation than not. That, and this is a good exercise.

**Comment by deidril** [comment]
got it. I'll look into it. I've already done a translation into french of the current en.json also. Do you want to include translations into the master project or prefer to have a module for each langage, using the babele module for example ?

**Comment by n0q** [comment]
Sure. If you wanted to add a fr.json, that would be pretty cool! Happy hunting!
