### ISSUE TITLE
Resetting Init not working

### ISSUE THREAD

**Issue by kcheu1** [n0q/hackmaster5e-fvtt#119]
When wanting to reset the initiative in the combat tracker, you can put a value  in, but then it goes to standard initiative die roll request.

**Comment by n0q** [comment]
Reproduced. Thanks!

The combat tracker's going to need a second pass to be usable, really. Will make a note of this one when I get to it (probably next after character class redesign).

**Comment by n0q** [comment]
Resolved by 0f602556cc607c75876f8ebe5255abd1f0c1425c. HMCombat.rollInitiative() wasn't checking to see if it had already been passed a formula or not. Unless I break it again, should see this corrected on the next update.

**Comment by n0q** [comment]
I ended up removing the context menu option for this entirely, in favor of the ability to just reach out and doubleclick an init to change it.
