### ISSUE TITLE
Error in media field from Manifest+

### ISSUE THREAD

**Issue by kakaroto** [n0q/hackmaster5e-fvtt#196]
Hi,
Seeing https://github.com/n0q/hackmaster5e-fvtt/commit/5f78406d910de40fbf24038b287172950ed7247e there's an error in the module.json, as the media field should be an array, not an object. This can cause issues with apps that use the `media` field and try to iterate through it (such as the Forge's Bazaar which crashed today because of that 😁 )
Thanks for fixing it!

**Comment by n0q** [comment]
Oops! Sorry about that!

**Comment by kakaroto** [comment]
> Oops! Sorry about that!

No worries, it helped me find a bug in my code and fix it  😄 
Thanks for the quick fix!
