### ISSUE TITLE
More a question than an issue.

### ISSUE THREAD

**Issue by discuit** [n0q/hackmaster5e-fvtt#280]
Could you advise me why the Skills populate with a value? I thought they all started at zero? Sorry, but I'm new to Hackmaster and a little confused. Thanks!

**Comment by n0q** [comment]
Hi, discuit!

There are actually two types of skills, and only one type does what you're thinking of.

Universal skills (the ones every character starts with) have a starting value based on the character's ability scores. These are things everyone knows how to do at least a little bit. Examples of Universal Skills: Listening, Observation, Persuasion. No one needs to be taught how to do these things, though one can certainly train to be better at them.

Non-Universal skills (the kind you don't start with) require training to use at all, so those do start with zero. Examples: Mining, Arcane/Divine Lore, Mathematics, and so on.

If you're brand new to Hackmaster and feeling a little lost, you should stop at the unofficial Kenzer and Co discord (check their website for an invitation link). You'll find plenty of people who can help or even demo the game for you.
