### ISSUE TITLE
-5 to skills at level 4

### ISSUE THREAD

**Issue by Jnov36** [n0q/hackmaster5e-fvtt#292]
When a character is leveled up to level 4, all skills have their totals reduced by 5.  I tested up to level 8 and it did not happen again.  I attempted to use use Bug Report but it did not look like it worked.

**Comment by n0q** [comment]
Did this character fall into Dishonorable honor in the process? The penalty for being in dishonor is a -5 to all skills and a -1 to all other roles, which the system implements. If this is the case, then you should see everything go back to normal after adding honor to get the character out of Dishonor.

**Comment by Jnov36** [comment]
That was the problem.  Sorry about that, didn't mean to waste your time.  Thanks for the quick reply.

**Comment by n0q** [comment]
No, not a waste of time at all, I promise! I appreciate that you took the time to write the issue. Glad it worked out!
