### ISSUE TITLE
Feature Request: Damage Bonus as a modifier for Classes

### ISSUE THREAD

**Issue by Smothmoth** [n0q/hackmaster5e-fvtt#293]
To facilitate expanded options for homebrew classes, would it be possible to add "Damage Bonus" as one of the options classes can get?

**Comment by n0q** [comment]
I really need to get away from hardcoded class features, so this sort of request isn't even a thing you have to make. But sure. This can be done easily enough! I'll put it in the next release, whenever that is. Hopefully sooner than later.
