### ISSUE TITLE
Feature Request: Wound Description Text Box

### ISSUE THREAD

**Issue by somenate** [n0q/hackmaster5e-fvtt#300]
Would be very nice to have a text box within the edit window of individual wounds to allow the player to type in descriptions of the specific wound like "Goblin Arrow" or "Wolverine Bite" in order to help keep track of the sources of wounds.

**Comment by n0q** [comment]
This should be fairly easy to handle, and has other uses. There's presently no way to denote a crit, and while I'm not going to be mechanically implementing crit effects any time soon, it's good to have a place to mention them.

Would it be acceptable to include an optional 'Note' field in the wound dialog and in the wound edit sheet, and then have a spot where comments can be seen via mouseover? I was thinking something like this mockup:

![image](https://github.com/n0q/hackmaster5e-fvtt/assets/7948363/143af2c0-1102-44bb-9764-9befee5aff00)

**Comment by n0q** [comment]
Added. This'll be present in the next release.
