### ISSUE TITLE
interactive combat chat cards

### ISSUE THREAD

**Issue by n0q** [n0q/hackmaster5e-fvtt#92]
combat cards should chain, so an attack provides a clickable for the defender, which potentially provides a clickable for the attacker, and so on.

**Comment by deidril** [comment]
Hi,
i was thinking to take this issue. As a first step, my idea was to implement alt+click to select a target as it's made in some modules :
- before rolling attack
- after rolling attack 
- after rolling attack, by the DM

then
- display target's name in the attack card
- if target is set after rolling, resend a new card or redisplay the old one if possible
- if card.target = himself, display defend option

**Comment by n0q** [comment]
I'm in the middle of a fairly heavy refactor of most parts of the game (replacing old placeholder code with something a little less ridiculous). Specifically, things having to do with stats of any kind are shifting. I'm worried some of the work you do here will break with some of my own PRs, once they get to the dev branch. Still, I don't believe this sort of addition would break very much, as I don't believe this issue heavily touches the areas being redesigned.

Even were this not the case, it's probably much wiser to keep this sort of thing stateless and simple until the game system matures a bit more. Many of the subsystems are little more than stubs and could shift wildly once they finally -are- refactored. It's wise to 'go small' to start.

I believe the following is more reasonable if you'd like to take this on.

- No targeting.
- Attack cards include a button which anyone may press to bring up a defend dialog.
- Defend cards include a button which anyone may press to bring up a damage dialog.
- Damage cards include a button which anyone may press to automatically wound their character.

This would provide a third way to interact with the game (Character sheet, combat macros, and chat carts), while cleaning up the chat manager in the process.

No targeting yet, simply because we'd need to push target data into the dialog->roll->chat pipeline somehow, and that system is quite immature. It would probably create technical debt for less value. Also to clarify, by 'card' I am referring to the Chat message sent to everyone. 

You'd want to create actual combat card templates (the one in templates/chat/spell.hbs was meant as a test of concept), and I imagine some scss additions might be necessary as well. Most of the necessary jQuery bindings probably exist already in actor-sheet.js. It's unclear if you could reuse them directly, or if ChatMessage would need to be overloaded in some fashion (which I suspect may be the case).

**Comment by deidril** [comment]
Thank for the answer.
If you do have issues that won't break up the current refactoring, and are newbie-friendly, i will glady look into them.
I may also wait the refactoring is complete if you think it's the best option for now.
Otherwhile i can do the suggested work on attack, defend and damage card :)

**Comment by n0q** [comment]
Yeah, it's just a fact that this issue touches on lots of the internals and probably isn't a great choice if you're not ready to dive in. I think you'd have a lot of trouble with this one. I'll try to earmark a few simpler tasks which need to get handled and will set them as good first issues, though. 

Learning the basics of foundry will help you immensely and I highly recommend the boilerplate system. You can find it and a tutorial [here](https://foundryvtt.wiki/en/development/guides/SD-tutorial/SD01-Getting-started). It's what I started with, and it made things a lot clearer. I saw you started a foundry system. You'd be hardpressed to find a better start for it than this!
